### PR TITLE
Wire up query-string endpoint

### PR DESCRIPTION
**Pull request by alran**
### Summary of Changes

This PR is to show how we are wiring up this PR https://github.com/lyft/amundsensearchlibrary/pull/51 at Square.

It will allow users to search using the full capabilities of Elasticsearch's built in lucene query parser

### Tests

I updated tests so that multiple search fields are allowed in search

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [x] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [x] PR includes a summary of changes, including screenshots of any UI changes. 
- [x] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public python functions and the classes in the PR contain docstrings that explain what it does
- [x] PR passes all tests documented in the [developer guide](https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/developer_guide.md#testing)
- [x] I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"

### CODE REVIEW

**Comment by ttannis** [comment]
@alran is this ready for review? (unsure only because we haven't been requested)

**Comment by alran** [comment]
I put this up to show @feng-tao how my PR on search would work. But it isn't ready for actual review until that search PR gets decided on!

**Comment by ttannis** [comment]
> I put this up to show @feng-tao how my PR on search would work. But it isn't ready for actual review until that search PR gets decided on!

Got it. Updated the tags on this so it doesn't get marked stale in the event things take a bit to get discussed. I'll take a peek at the PR in search as well. There's a chance this could become relevant as here at Lyft we're looking to start added some search filtering capabilities. If this is something you might be looking at on your end as well, let us know!

**Comment by alran** [comment]
yep we are very interested in giving our users more control of search! Let me know what you think of the search PR as well. It sounds like the library I used for Lucene Query Parsing has a not-ideal license

**Comment by ttannis** [comment]
Closing this PR, as it will become obsolete due to the work in https://github.com/lyft/amundsenfrontendlibrary/pull/384.

**Pull request closed without merging**
