### PR TITLE
feat: Added Redash logo, configured as supported dashboard source

### PR DESCRIPTION
**Pull request by jonhehir**
### Summary of Changes

https://github.com/lyft/amundsendatabuilder/pull/300 will make it possible to load Redash dashboards into Amundsen. The results look even better with logos! 😄 

### Tests

none

### Documentation

none

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [X] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [X] PR includes a summary of changes, including screenshots of any UI changes. 
- [X] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [X] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public python functions and the classes in the PR contain docstrings that explain what it does
- [X] PR passes all tests documented in the [developer guide](https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/developer_guide.md#testing)

### CODE REVIEW

**Comment by feng-tao** [comment]
once everything is merged, we should update https://github.com/lyft/amundsen#dashboard-connectors to include redash as well.

**Comment by feng-tao** [comment]
will merge once the databuilder is merged.

**Comment by ttannis** [comment]
> I will merge this pr once the databuilder is merged.

Sounds good, I was also waiting on finalized backend support.

**Comment by feng-tao** [comment]
the backend is merged in databuilder. We could merge this one as well.

**Pull request merged**
