### PR TITLE
Change stat collection info from tooltip to label

### PR DESCRIPTION
**Pull request by danwom**
This commit addresses frequent feedback that the stats calculations are not accurate. The stats are accurate, but for specific time periods. The details were hidden in a tooltip that wasn't very obvious for the user.

### CODE REVIEW

**Comment by danwom** [comment]
Preview of new stats collection info.

screen shot 2019-03-04 at 4 04 42 pm

**Comment by feng-tao** [comment]
@danwom , not sure if we want to attach the screenshoot given it may provide sensitive information for others.

**Comment by danwom** [comment]
@feng-tao the screenshot I provided was with mock data. I also changed the location/style of info text to the bottom.

screen shot 2019-03-04 at 4 23 54 pm

**Comment by feng-tao** [comment]
thanks @danwom , the screenshot lgtm

**Pull request merged**
