### PR TITLE
Implements new utility methods to handle the request headers

### PR DESCRIPTION
**Pull request by verdan**
### Summary of Changes

For now, the request headers can be set using config variable. This PR updates the mechanism to allow to pass a function to generate headers dynamically based on the app state by passing in the current app. This will help pass the authorization headers across different microservices i.e., JWT tokens. 
Also, refactored the code and put the call and headers within the single place in the codebase. 

### Tests

No tests are added as this simply refactors the code a bit. 

### Documentation

No documentation needed. Added the docstring for newly added functions. 

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [X] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [X] PR includes a summary of changes, including screenshots of any UI changes. 
- [X] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [X] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public python functions and the classes in the PR contain docstrings that explain what it does
- [X] PR passes all tests documented in the [developer guide](https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/developer_guide.md#testing)
- [X] I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"

### CODE REVIEW

**Comment by verdan** [comment]
Ready For review
@feng-tao

**Comment by feng-tao** [comment]
thanks @verdan . The code LGTM, cc @ttannis to add additional eye :)

**Comment by ttannis** [comment]
@verdan will take a look today. We do have a small UI bug that we have to fix before pushing the new version, but we'll be sure to fix that today as well so we can push the new version.

**Comment by ttannis** [comment]
We will merge and push a library version after resolving #144

**Comment by feng-tao** [comment]
@ttannis I think it is fine to push this one in first. We could resolve the user issue with a new minor version.

@verdan just publish it to pypi.

**Pull request merged**
