### PR TITLE
Bump the search version in docker script

### PR DESCRIPTION
**Pull request by feng-tao**
### Summary of Changes

We did a refactor on search model. We should bump the version.

### Tests

_What tests did you add or modify and why? If no tests were added or modified, explain why. Remove this line_

### Documentation

_What documentation did you add or modify and why? Add any relevant links then remove this line_

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [ ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [ ] PR includes a summary of changes, including screenshots of any UI changes. 
- [ ] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public python functions and the classes in the PR contain docstrings that explain what it does
- [ ] PR passes all tests documented in the [developer guide](https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/developer_guide.md#testing)
- [ ] I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"

### CODE REVIEW

**Comment by feng-tao** [comment]
cc @youngyjd @jinhyukchang @jornh

**Comment by jornh** [comment]
Please bump the frontend (also setup.py) as well. It needs a new container build to light up the new sweet stuff from https://github.com/lyft/amundsenfrontendlibrary/pull/196

**Comment by feng-tao** [comment]
@jornh , version bump as well. @ttannis @danwom , I think we also need to bump the setup.py version in FE from time to time which is beneficial for external people as they depends on the docker/pypi version.

**Comment by ttannis** [comment]
> @jornh , version bump as well. @ttannis @danwom , I think we also need to bump the setup.py version in FE from time to time which is beneficial for external people as they depends on the docker/pypi version.

Before we start bumping the releases regularly, I hope to take a step back to evaluate how we want to approach our frontend releases. As of now the way we're managing this is not that great because the frontend code has had many things perpetually "in development" for a while. I was concerned about creating a negative experience for the community -- especially new users -- by creating releases with features that are still being developed. My intent is to hopefully establish something better for the community starting with our next major version, where we regularly bump only when something is ready (or bug fix is needed).

**Pull request merged**
