### PR TITLE
docker-amundsen.yml pegging to tagged versions

### PR DESCRIPTION
**Pull request by jornh**
### Summary of Changes

* uses tagged versions of the three Amundsen services
* sets PROXY_ENDPOINT for the elasticsearch container
   which _should_ make it JustWork(tm) with docker-engine
   based setups. NOTE this requires the 1.0.2 version of the
   search service container
* similarly sets PROXY_HOST for neo4j

### Tests

No changes to tests. We don't have tests for docker-compose (though I think I saw someone building tests for container integrations as well)

**NOTE** This PR relies on that the Amundsen search service container v 1.0.2 gets tagged and pushed to DockerHub. Do not merge before that has been pushed! 

### Documentation

No Documentation changes. I think as followup PRs we can improve docs though - e.g. document `PROXY_HOST` etc. environment vars.

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [x] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [x] PR includes a summary of changes, including screenshots of any UI changes. 
- [x] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public python functions and the classes in the PR contain docstrings that explain what it does
- [x] PR passes all tests documented in the [developer guide](https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/developer_guide.md#testing)
- [x] I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"

### CODE REVIEW

**Comment by jornh** [comment]
You're most welcome @jinhyukchang!

I hope you noticed the dependency for this on the not-yet-tagged and pushed to DockerHub 1.0.2 of the search service: https://github.com/lyft/amundsensearchlibrary/releases ... and that you plan for that to follow shortly 😉 👍

**Comment by jornh** [comment]
Otherwise we'll soon have people reporting they experience this:

``` bash
$ docker-compose -f docker-amundsen.yml up
Pulling amundsensearch (amundsendev/amundsen-search:1.0.2)...
ERROR: manifest for amundsendev/amundsen-search:1.0.2 not found: manifest unknown: manifest unknown
```

**Comment by jinhyukchang** [comment]
> Otherwise we'll soon have people reporting they experience this:
> 
> ```shell
> $ docker-compose -f docker-amundsen.yml up
> Pulling amundsensearch (amundsendev/amundsen-search:1.0.2)...
> ERROR: manifest for amundsendev/amundsen-search:1.0.2 not found: manifest unknown: manifest unknown
> ```

Got it. Just published 1.0.2!
https://github.com/lyft/amundsensearchlibrary/releases/tag/v1.0.2

**Comment by jornh** [comment]
🎉

**Pull request merged**
