### PR TITLE
Include the js folder in typescript config to fix "npm run tsc"

### PR DESCRIPTION
**Pull request by alran**
### Summary of Changes

This PR fixes `npm run tsc`, which was error-ing previously.

Addresses [this issue](https://github.com/lyft/amundsenfrontendlibrary/issues/145)

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [x] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [x] PR includes a summary of changes, including screenshots of any UI changes. 
- [x] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public python functions and the classes in the PR contain docstrings that explain what it does
- [x] PR passes all tests documented in the [developer guide](https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/developer_guide.md#testing)
- [x] I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"

### CODE REVIEW

**Comment by alran** [comment]
is there a way to re kickoff that CLA check?

**Comment by jornh** [comment]
@alran just click the blue `Details` link in the right side of the CLA ckeck section, and you’re lead through signing by using your GitHub account as far as I can remember!

**Comment by feng-tao** [comment]
@alran I think @jhettler encountered this issue before in (https://github.com/lyft/amundsendatabuilder/pull/23) . My understanding is that you need to config the github user.name and user.email locally first(could confirm with git config --list), then push to the branch which should work. There are some similar discussions in https://github.com/lyft/amundsendatabuilder/pull/23 . Let us know if it works or not.

**Comment by feng-tao** [comment]
nice 👍

**Comment by jornh** [comment]
Cool @alran - not having spent a lot of time with TypeScript I didn't know about `tsc`

Contrats on your first Amundsen PR 🎉

**Pull request merged**
