### PR TITLE
fix: Getting tooltip on edit button of Column Description if un-editable

### PR DESCRIPTION
**Pull request by dikshathakur3119**
### Summary of Changes

We have provided feature for making table and column description un-editable, in this PR we are providing link to source file from column's edit button if someone wants to change column description at source file.
Edit link and source is same as table source link. 

### Tests
NA

### Documentation

NA

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [ ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [ ] PR includes a summary of changes, including screenshots of any UI changes. 
- [ ] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public python functions and the classes in the PR contain docstrings that explain what it does
- [ ] PR passes all tests documented in the [developer guide](https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/developer_guide.md#testing)

### CODE REVIEW

**Comment by dikshathakur3119** [comment]
@ttannis  @allisonsuarez  let me know if this is good way to pass `editText` and `editUrl` to `ColumnListItem`. I am planning to add a unit test case as well.

**Comment by allisonsuarez** [comment]
> @ttannis @allisonsuarez let me know if this is good way to pass `editText` and `editUrl` to `ColumnListItem`. I am planning to add a unit test case as well.

I think this makes sense assuming that all of the column descriptions would be uneditable rather than just individual columns being un-editable. I think is how this is supposed to work so looks good to me.

**Comment by allisonsuarez** [comment]
> @ttannis @allisonsuarez let me know if this is good way to pass `editText` and `editUrl` to `ColumnListItem`. I am planning to add a unit test case as well.

it also follows the same way this is being done for editable descriptions which is good for consistency.

**Comment by ttannis** [comment]
> > @ttannis @allisonsuarez let me know if this is good way to pass `editText` and `editUrl` to `ColumnListItem`. I am planning to add a unit test case as well.
> 
> I think this makes sense assuming that all of the column descriptions would be uneditable rather than just individual columns being un-editable. I think is how this is supposed to work so looks good to me.

Agreed, you mentioned feeling as if you were making components messy, but passing properties from parents to children is a regular thing to do. This implementation is fine from my perspective as well.

**Pull request merged**
