### PR TITLE
Feature/Instructions to install Amundsen using AWS ECS

### PR DESCRIPTION
**Pull request by joaolcorreia**
### Summary of Changes

Added documentation and instructions to run via AWS ECS on **docs/instalation-aws-ecs**. The folder includes step by step instructions and the necessary configuration files.

While it is far from a complete production setup, it works.

### CODE REVIEW

**Comment by joaolcorreia** [comment]
Just completed the CLA.

**Comment by joaolcorreia** [comment]
Thank you for the reminder @jinhyukchang !. In due time I'll have to build a new image with a proper web server.

**Comment by jinhyukchang** [comment]
> Thank you for the reminder @jinhyukchang !. In due time I'll have to build a new image with a proper web server.

Missed this response. Synced offline and there will be a disclaimer in the doc that this instruction is not for production.

**Comment by jinhyukchang** [comment]
@joaolcorreia 
Please ping me once you create new PR.

**Pull request closed without merging**
