### PR TITLE
chore[fe]: apply license headers for fe (html, scss, tsx)

### PR DESCRIPTION
**Pull request by feng-tao**
### Summary of Changes

_Include a summary of changes then remove this line_

### Tests

_What tests did you add or modify and why? If no tests were added or modified, explain why. Remove this line_

### Documentation

_What documentation did you add or modify and why? Add any relevant links then remove this line_

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [ ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [ ] PR includes a summary of changes, including screenshots of any UI changes. 
- [ ] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public python functions and the classes in the PR contain docstrings that explain what it does
- [ ] PR passes all tests documented in the [developer guide](https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/developer_guide.md#testing)

### CODE REVIEW

**Comment by ttannis** [comment]
Do we really have to put this on every file? Is there some information you can provide about this and what it means?

**Comment by feng-tao** [comment]
I don't have much context, but mostly follow what LFAI suggested. This is from one email Mark cc from LFAI.
```
 We did notice also that although the repos have top-level LICENSE files, most of the source code files do not have license headers or references in them. We encourage including a license statement in each file where reasonably possible; this provides many benefits, including making it easier for other projects to reuse the open source files without losing track of their license information. One easy way to do this is by adding a single line comment to the top of each file with its SPDX license ID, such as the following for Amundsen source code:

SPDX-License-Identifier: Apache-2.0

or the following for Amundsen documentation, assuming it adopts CC-BY-4.0 for documentation:

SPDX-License-Identifier: CC-BY-4.0

More information about these SPDX short-form identifiers can be found at https://spdx.dev/ids. Using the SPDX license ID will save you from putting a full licensing header and it is also discoverable by source code scanning tools. 
```

Then I look at an existing example of one of LFAI project from UBER (https://github.com/pyro-ppl/pyro/blob/dev/pyro/ops/arrowhead.py#L1-L2) and they did this. Hence that's how I come up with the pr. I think we only need to apply the headers to source code in a best effort.

**Comment by ttannis** [comment]
Also have concerns about what this means legally. For example with some of the css and style choices (example: All color specifications in `_colors.scss`) are concepts that we are currently allowed take from Lyft's internal design specifications to use in this tool. 

But then if we're now applying some copyright to that, I wonder is that will change the decision we originally got from the people who work on Lyft Product Language. I can look into it, but first trying to understand the implications of this copyright text.

**Comment by feng-tao** [comment]
good point @ttannis , unfortunately I didn't see any existing project within LFAI that have code using css or HTML. Let me cc you in the same email Mark cc me so that you could clarify with the LFAI folks

**Pull request merged**
