### PR TITLE
add Roadmap

### PR DESCRIPTION
**Pull request by philippemizrahi**
### Summary of Changes

Add a roadmap listing Amundsen's Mission and Vision, what we are currently developing and what we will tackle next. This also include some links to designs and specs.

### CODE REVIEW

**Comment by philippemizrahi** [comment]
PTAL @ttannis

**Comment by ttannis** [comment]
Do you mind also adding this https://github.com/lyft/amundsen?

I'm starting to rethink our approach to our umbrella repo, in regards to the fact that we've been waiting to make the switch since https://github.com/lyft/amundsen still doesn't have all the ideal content we want. However it creates extra effort to keep the two in sync as we work through this process, which is a shame because that is effort that we could be putting into getting the stuff done in the first place. It will be great if you could submit this in https://github.com/lyft/amundsen, and perhaps we'll just maintain that copy going forward since this one will eventually be deleted. I'll raise this to the team this week and see how they feel.

**Comment by philippemizrahi** [comment]
Agreed that it's better to switch sooner than later. To be sure I understand correctly, you are suggesting that I delete the PR in amundsenfrontendlibrary and open it in amundsen?

**Comment by ttannis** [comment]
> Agreed that it's better to switch sooner than later. To be sure I understand correctly, you are suggesting that I delete the PR in amundsenfrontendlibrary and open it in amundsen?

Nope you can keep this here. Only create another one in amundsen, and if you have to make future edits and updates, might as well just update the one that will be in amundsen. It helps me out because so far all I can do is just been track all PRs that edit documentation, and then every week or two copy-paste those updates into amundsen and just hope I didn't miss anything. 😢

**Comment by philippemizrahi** [comment]
Should we delete this one and link the roadmap link in the readme.md to the roadmap in the amundsen repo?

**Comment by philippemizrahi** [comment]
also, should we add a line at the beginning of the readme of this repo saying that we are trying to move to the amundsen repo?

**Comment by jornh** [comment]
My 2 cent: 

@philippemizrahi 👍 on your two last comments. (Because `roadmap.md` really never existed)

For some of the more high traffic of the existing “umbrella” docs (probably `installation.md` and `architecture.md` - not sure about `configuration.md` -  you have the numbers I don’t) I’d vote for that for a while until traffic decreases that the existing documents are kept as stub documents with a link to the new location. This is to not end with an experience with dead links from Slack etc. - like you would experience here: https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/deleted-roadmap.md

I really love the focus on near term goals in the roadmap. Better to keep high(er) velocity on a few things and get them done. Looking forward to see notification come to fruition!

**Comment by ttannis** [comment]
> also, should we add a line at the beginning of the readme of this repo saying that we are trying to move to the amundsen repo?

I don't think so, there's no specific action that we'd want other to take. I'll think of a concrete plan and timeline to propose for this next week.

**Comment by feng-tao** [comment]
@philippemizrahi For reference, I prefer we should add everyone or even in the community to review this pr. And some of the term(like 2020) is too lyft specific which I am not sure if we should include.

WDYT @jinhyukchang @markgrover

**Comment by feng-tao** [comment]
I will look at this doc in more detail next week.

**Pull request merged**
