### PR TITLE
Establish Unit Tests

### PR DESCRIPTION
**Pull request by ttannis**
This repo already has Jest included as our unit testing framework for our JavaScript/TypeScript code, and we aim to reduce our unit test tech debt moving forward. This PR does the following:

1. Updates previous Jest configs. We anticipate that we will improve and refine these configs as needed. For reference: https://jestjs.io/docs/en/configuration
2. Deletes all previous tests -- they ultimately became throw-aways as we continued development without prioritizing this tech debt.
3. Deletes all unused components -- `ConfirmDeleteButton` became a throw-away component after our new design standards for buttons and editable content.
4. Adds unit test coverage for `js/components/common` as a starting point. _Note: `EditableText` is one outlier that will have to be cleaned up and refactored for better unit testing._
5. Adds unit test script to our Travis tests.
6. Minor syntax fixes for lint/warnings.

**Actual Coverage Report**
image

### CODE REVIEW

**Comment by ttannis** [comment]
@verdan @danwom 

This is a work in progress. I will request and official review when ready, however I'm posting this PR its goals ahead of time for some transparency as well as to welcome any input along the way.

**Comment by feng-tao** [comment]
cc @verdan FYI

**Comment by feng-tao** [comment]
@ttannis , with this change committed, we could close this https://github.com/lyft/amundsenfrontendlibrary/issues/84 ?

**Comment by ttannis** [comment]
> @ttannis , with this change committed, we could close this #84 ?

I'll close it out after verifying all the scripts don't throw any errors. What is worth calling out is that the linting is run as part of `npm run build`, which is run in Travis CI. I'm curious how there was a version of the code that passed a Travis build but still had lint errors, so I'll timebox some investigation before closing #84.

**Pull request merged**
