### PR TITLE
Merge master into feature/dashboard

### PR DESCRIPTION
**Pull request by ttannis**
### Summary of Changes

Feature branch is stale against master and should get updated before new development.

### Tests

N/A

### Documentation

N/A

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [x] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [x] PR includes a summary of changes, including screenshots of any UI changes. 
- [x] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public python functions and the classes in the PR contain docstrings that explain what it does
- [x] PR passes all tests documented in the [developer guide](https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/developer_guide.md#testing)

### CODE REVIEW

**Comment by ttannis** [comment]
@csteez @danwom 

This merge was not all that bad even though there's been a lot of work merged. Pasting the list of auto-merges and conflicts that were reported, and you could just check these reported files and ensure anything you worked on in those files look good.

```
Removing tests/unit/utils/notification/__init__.py
Auto-merging amundsen_application/static/js/interfaces/TableMetadata.ts
Auto-merging amundsen_application/static/js/fixtures/globalState.ts
Auto-merging amundsen_application/static/js/ducks/rootSaga.ts
Auto-merging amundsen_application/static/js/ducks/rootReducer.ts
CONFLICT (content): Merge conflict in amundsen_application/static/js/ducks/rootReducer.ts
Auto-merging amundsen_application/static/js/components/common/ResourceListItem/TableListItem/index.tsx
Removing amundsen_application/static/js/components/common/Inputs/CheckBoxItem/styles.scss
CONFLICT (modify/delete): amundsen_application/static/js/components/TableDetail/styles.scss deleted in HEAD and modified in origin. Version origin of amundsen_application/static/js/components/TableDetail/styles.scss left in tree.
Auto-merging amundsen_application/static/js/components/TableDetail/index.tsx
Auto-merging amundsen_application/static/jest.config.js
Auto-merging amundsen_application/static/css/_layouts.scss
CONFLICT (content): Merge conflict in amundsen_application/static/css/_layouts.scss
Auto-merging amundsen_application/static/css/_icons.scss
CONFLICT (content): Merge conflict in amundsen_application/static/css/_icons.scss
Auto-merging amundsen_application/__init__.py
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by csteez** [comment]
I went through the files I've touched and it looks good!

**Comment by danwom** [comment]
Given that we only have two commits on the dashboard feature, it might be easier to just rebase.

**Comment by ttannis** [comment]
> Given that we only have two commits on the dashboard feature, it might be easier to just rebase.

True could have made the exception and rebased in this case. I'll go ahead and merge this though since it's ready.

**Comment by ttannis** [comment]
> > Given that we only have two commits on the dashboard feature, it might be easier to just rebase.
> 
> True could have made the exception and rebased in this case. I'll go ahead and merge this though since it's ready.

^ @danwom instantly regretting that decision. 😞 After merging the diff against master is messed up again. Still not understanding why but I'll fix it.

**Pull request merged**
