### PR TITLE
fix: Wrap dashboard description in .editable-text to enforce description styles

### PR DESCRIPTION
**Pull request by jonhehir**
### Summary of Changes

Right now, dashboard descriptions aren't styled the same way as table descriptions, since dashboard descriptions are not in `.editable-text`. The main consequence of this is that headings in dashboard descriptions can be very large.

image

### Tests

None

### Documentation

None

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [X] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [X] PR includes a summary of changes, including screenshots of any UI changes. 
- [X] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [X] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public python functions and the classes in the PR contain docstrings that explain what it does
- [X] PR passes all tests documented in the [developer guide](https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/developer_guide.md#testing)

### CODE REVIEW

**Comment by feng-tao** [comment]
close and open PR fixed the CLA check issue.

**Comment by ttannis** [comment]
> ### Summary of Changes
> Right now, dashboard descriptions aren't styled the same way as table descriptions, since dashboard descriptions are not in `.editable-text`. The main consequence of this is that headings in dashboard descriptions can be very large.
> 
> image
> 
> ### Tests
> None
> 
> ### Documentation
> None
> 
> ### CheckList
> Make sure you have checked **all** steps below to ensure a timely review.
> 
> * [x]  PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
>   
>   * In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
> * [x]  PR includes a summary of changes, including screenshots of any UI changes.
> * [x]  PR adds unit tests, updates existing unit tests, **OR** documents why no test additions or modifications are needed.
> * [x]  In case of new functionality, my PR adds documentation that describes how to use it.
>   
>   * All the public python functions and the classes in the PR contain docstrings that explain what it does
> * [x]  PR passes all tests documented in the [developer guide](https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/developer_guide.md#testing)

@jonhehir to make sure I understand the issue, can you confirm  the markdown you are using in this situation. In markdown you can control which header tags you use, so could you not use the markdown for a smaller header?

**Comment by jonhehir** [comment]
Sure, the Markdown in that screenshot uses either an `h1` or `h2` (I don't recall). The styles that are ordinarily applied to `EditableText` restrict the max size of headers (and also adjust spacing a bit) [https://github.com/lyft/amundsenfrontendlibrary/blob/master/amundsen_application/static/js/components/common/EditableText/styles.scss](here). While it is certainly possible to make smaller headings by using a different header level, these descriptions are being imported from another system, so it's not obvious to the user writing the Markdown how it will appear in Amundsen.

**Comment by ttannis** [comment]
> Sure, the Markdown in that screenshot uses either an `h1` or `h2` (I don't recall). The styles that are ordinarily applied to `EditableText` restrict the max size of headers (and also adjust spacing a bit) [here](https://github.com/lyft/amundsenfrontendlibrary/blob/master/amundsen_application/static/js/components/common/EditableText/styles.scss). While it is certainly possible to make smaller headings by using a different header level, these descriptions are being imported from another system, so it's not obvious to the user writing the Markdown how it will appear in Amundsen.

Thanks @jonhehir. If that's the case I think I will introduce an alternative fix here in my spare time. 

`.editable-text` is a style for the `EditableText` component, and it is now getting applied to something that is not an `EditableText` component.  The change produces the desired effects, but to avoid unintended CSS side effects in the future I will prefer to:
1. Keep the markup of the component unchanged for something that can be done via CSS rules.
2. Apply css rules that explicitly apply to markdown wrapper.

**Comment by jonhehir** [comment]
That sounds like a good idea to me. My apologies for applying the class a bit haphazardly. When I initially made the PR, I didn't take note of the fact that these styles are actually defined in the `EditableText` component.

**Comment by ttannis** [comment]
> That sounds like a good idea to me. My apologies for applying the class a bit haphazardly. When I initially made the PR, I didn't take note of the fact that these styles are actually defined in the `EditableText` component.

No problem, iterations can be expected. Often times there are a lot of different way to achieve the intended results.

**Pull request merged**
