### PR TITLE
WIP Proposal: GitHub board for roadmap

### PR DESCRIPTION
**Pull request by jornh**
Location on my fork added in https://github.com/lyft/amundsenfrontendlibrary/pull/107/commits/8fe61b76d27110ef7187c2222d84c3472b2dbc08 is only for illustrative purposes.

Another commit before merge should of course point to https://github.com/lyft/amundsenfrontendlibrary/projects in place of what I put on my fork: https://github.com/jornh/amundsenfrontendlibrary/projects

To test out the WIP go to the [README.md](https://github.com/jornh/amundsenfrontendlibrary/tree/jornh-roadmap-patch-1#roadmap) on my branch and click the Roadmap link.

Note still working on fleshing out the details with ~~including a few illustrations (from slide link in lyft/amundsenfrontendlibrary#41 e.g. https://www.slideshare.net/taofung/strata-sf-amundsen-presentation/64)~~ + “call to action” on where/how interested folks can best get going and participate ... adding more placeholder issues etc.

But I’m throwing this out there in this *super rough form* now ... just for the sake of sharing 🙂

### CODE REVIEW

**Comment by feng-tao** [comment]
thanks @jornh :)
cc a few folks here
@markgrover @philippemizrahi (both are product managers from Lyft)
@jinhyukchang @ttannis @danwom (engineers from Lyft)
@verdan @bolkedebruin (our friends from ING who are building integration with Apache Atlas)

**Comment by jornh** [comment]
@feng-tao thank you for looping in more people as you found relevant. Very eager to hear thoughts/suggestions/concerns/additions from y'all - and really anyone!

With the content currently added I *tried* to stay true to what I could just pick up from what has already been shared. I think I will stop adding more until I get your input.

Personally I have a few places where the "jury is still out" and I'm undecided:

1. The intention was to reduce maintaining/duplicating to much textual content - and just be able to link to live issues and PR's. Their state will be reflected on the board (red, green, blue), and you can combine/bundle and mix with pure textual `Note` cards

1. I really want the top level roadmap text-blurp https://github.com/jornh/amundsenfrontendlibrary/projects to be close to the **Board** page, also it's very handy using the top level `:kanban: Projects` GitHub tab. But AFAICT there's a problem that only few people will be able to maintain it (how would you open a PR against the text blurp?). *Needless to say I of course volunteer to help out with maintaining*

1. Not sure how the **Board** page with 1.x, 2.0, 3.0 will work out maintenance-wise (pro: Nice to have full overview on _one_ page) vs splitting into separate project boards for each phase (I've seen [SchemaSpy](https://github.com/SchemaSpy/SchemaSpy/projects) use the split approach and [Metabase](https://github.com/metabase/metabase/projects/1) use[d] the "global" approach).

Maybe it's simply to try it out for real, and adjust from there. WDYT?

So, just to repeat myself once more:
> Very eager to hear thoughts/suggestions/concerns/additions from y'all - and really anyone!

The ball is in your court now...

**Comment by philippemizrahi** [comment]
Love it @jornh!  💯really exciting :) I will share some more flavor on what we have in mind for the roadmap on the Lyft side soon

**Comment by jornh** [comment]
Great, if you think it’s useful as a way to maintain roadmap going forward. 

And now you really triggered my curiosity on what you guys have cooking, oh well, let me know how any ideas on how I can best assist on this when you can.

**Comment by jornh** [comment]
I will retire this draft PR in favor of https://github.com/lyft/amundsen/pull/20 (in the umbrella ☂ repo)

My draft content will also get a “redirect” pointer to the new roadmap document, when it’s merged, as I suggested in https://github.com/lyft/amundsenfrontendlibrary/pull/235#issuecomment-514466690

**Pull request closed without merging**
