### PR TITLE
Merge feature people

### PR DESCRIPTION
**Pull request by danwom**
Merging branch `feature/people` into `master`.

`feature/people` adds support for multiple search resources, tabbed results, breadcrumbs, and profile pages. These features are currently disabled/hidden (except tabs and breadcrumbs).

### CODE REVIEW

**Comment by danwom** [comment]
The last commit has some new changes that have not been reviewed yet.

**Comment by feng-tao** [comment]
cc @jinhyukchang

**Comment by danwom** [comment]
@feng-tao I'll cleanup the test code in a follow up commit.

**Comment by feng-tao** [comment]
thanks @danwom

**Pull request merged**
